### ISSUE TITLE
update dev dependencies

### ISSUE THREAD

**Issue by titouancreach** [titouancreach/vuejs-redux#24]
The devDependencies are not up to date, we probably need to do a npm upgrade and check if the test and build don't break

**Comment by MohammadHasham** [comment]
try ```npm install```

**Comment by titouancreach** [comment]
Npm install will not update the dependencies where the major version number has changed

**Comment by deerawan** [comment]
@titouancreach can I work on this issue?

**Comment by titouancreach** [comment]
Sure!don't need to ask 😊every help is welcomed!

**Comment by titouancreach** [comment]
Could you please include de package-lock.json in this pr? I forgot to add it

**Comment by deerawan** [comment]
@titouancreach sure 👍

**Comment by titouancreach** [comment]
I let it open for the examples :) This has been resolved with https://github.com/titouancreach/vuejs-redux/pull/39 by @deerawan. We can still update the example dependencies. Maybe it will be more complicated since webpack 4 comes with breaking changes

**Comment by titouancreach** [comment]
Closes by #54
