### ISSUE TITLE
Add prettier 

### ISSUE THREAD

**Issue by titouancreach** [titouancreach/vuejs-redux#29]
That would be cool if we add a prettierrc file, add a command to format in the package.json, and add prettier in the dev dependencies

**Comment by khrystuk** [comment]
Hey @titouancreach! I would like to work on it

**Comment by titouancreach** [comment]
No problem, go ahead. Thanks a lot! 😊

**Comment by titouancreach** [comment]
No problem, go ahead. Thanks a lot! 😊

**Comment by titouancreach** [comment]
There is some rule I like in the prettier rc, no semicolumn, single quote, es5trailing commas, and no space in bracket spacing 😀

**Comment by khrystuk** [comment]
Done in #30.

**Comment by titouancreach** [comment]
Wow nice! Maybe we should ignore the bundle.js?

**Comment by titouancreach** [comment]
Or all the dist directory?

**Comment by khrystuk** [comment]
@titouancreach  Added .prettierignore

**Comment by titouancreach** [comment]
Awesome, lgtm, I merge this asap, thanks again! :relaxed:

**Comment by vvscode** [comment]
Also added lint-staged configuration https://github.com/titouancreach/vuejs-redux/pull/32/files

**Comment by titouancreach** [comment]
thanks @vvscode !
