### ISSUE TITLE
Add integration with CI ( like TravisCI ) to run tests on PR

### ISSUE THREAD

**Issue by vvscode** [titouancreach/vuejs-redux#33]
It would be great add CircleCI / TravisCI or something similar to check code on PR

**Comment by titouancreach** [comment]
I totally agree!

**Comment by vvscode** [comment]
@titouancreach  I'll do, but after merging you need autorize on Travis CI and enable integration with repo ( that should be done by repo owner )

**Comment by vvscode** [comment]
ok

**Comment by vvscode** [comment]
just to check - I got failing tests on master branch. Do you?

**Comment by titouancreach** [comment]
This is working very well, thanks again :)
