### ISSUE TITLE
replace npm run dev to npm run start

### ISSUE THREAD

**Issue by titouancreach** [titouancreach/vuejs-redux#35]
create react app and many other project use `npm start` to start the dev server, maybe we can change the name script in the example to match this

**Comment by keeganthomp** [comment]
I'll work on this 👍

**Comment by titouancreach** [comment]
Super! @keeganthomp

**Comment by keeganthomp** [comment]
JK. Looks like Marcelo got it :)

**Comment by titouancreach** [comment]
Yes he was faster :) there is still some issues in the list :D
