### ISSUE TITLE
bundle.js arrow functions incompatible with IE11

### ISSUE THREAD

**Issue by te-blank** [titouancreach/vuejs-redux#51]
[IE11 does not support arrow functions](https://caniuse.com/#feat=arrow-functions), which are present in the [bundle.js / main script](https://github.com/titouancreach/vuejs-redux/blob/master/bundle.js#L15).

Perhaps the `.babelrc` file could be adjusted to ensure the `bundle.js` output is compatible with IE11, via [babel's preset-env](https://babeljs.io/docs/en/next/babel-preset-env.html)?

**Comment by titouancreach** [comment]
I agree, I never had the need to support IE11, this is why the bundle works only for modern browser!
Do you want to do a PR ? I will be happy to merge it and deploy a new version!

**Comment by titouancreach** [comment]
Just out of curiosity, are you using a bundler ?

**Comment by te-blank** [comment]
We are using a bundler, but in our case we're not transpiling this npm dependency -- PR inbound!
